services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - order-service

  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb+srv://prerana28:prerana28@cluster0.zm6aijh.mongodb.net/order_db?retryWrites=true&w=majority&appName=Cluster0"

  payment-service:
    build: ./payment-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb+srv://prerana28:prerana28@cluster0.zm6aijh.mongodb.net/payment_db?retryWrites=true&w=majority&appName=Cluster0"

  inventory-service:
    build: ./inventory-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb+srv://prerana28:prerana28@cluster0.zm6aijh.mongodb.net/inventory_db?retryWrites=true&w=majority&appName=Cluster0"

  shipping-service:
    build: ./shipping-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb+srv://prerana28:prerana28@cluster0.zm6aijh.mongodb.net/shipping_db?retryWrites=true&w=majority&appName=Cluster0"

  delivery-service:
    build: ./delivery-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb+srv://prerana28:prerana28@cluster0.zm6aijh.mongodb.net/delivery_db?retryWrites=true&w=majority&appName=Cluster0"

  notification-service:
    build: ./notification-service
    ports:
      - "8086:8086"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb+srv://prerana28:prerana28@cluster0.zm6aijh.mongodb.net/notification_db?retryWrites=true&w=majority&appName=Cluster0"
