spring.application.name=notification-service
server.port=8086

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://prerana28:prerana28@cluster0.zm6aijh.mongodb.net/notification_db?retryWrites=true&w=majority&appName=Cluster0}
