spring.application.name=order-service
server.port=8081

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://prerana28:prerana28@cluster0.zm6aijh.mongodb.net/order_db?retryWrites=true&w=majority&appName=Cluster0}

service.inventory.url=http://localhost:8083
service.payment.url=http://localhost:8082
service.shipping.url=http://localhost:8084
service.notification.url=http://localhost:8086
