spring.application.name=api-gateway
server.port=8080

service.order.url=http://localhost:8081
service.payment.url=http://localhost:8082
service.inventory.url=http://localhost:8083
service.shipping.url=http://localhost:8084
service.delivery.url=http://localhost:8085
service.notification.url=http://localhost:8086
