spring.application.name=shipping-service
server.port=8084

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://prerana28:prerana28@cluster0.zm6aijh.mongodb.net/shipping_db?retryWrites=true&w=majority&appName=Cluster0}

service.delivery.url=http://localhost:8085
service.notification.url=http://localhost:8086
